# Build and publish Docker images for multible architectures.
# 
# Pushing an image to codeberg as container registry,
# package owner will be the repo owner.
#
# this config also shows usage of yaml aliases and
# was taken from https://codeberg.org/6543/docker-images/src/commit/37e29c227717c1c07d2776cddcf14725bf952875/.woodpecker/hello.yml

when:
  branch: main

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/flohmarkt

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
      dry_run: true
      repo: *repo
      tags: latest
    when:
      event: pull_request
      path: *file

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      event: push
      path: *file